sharepoint:
  site_url: "https://pernodricard-my.sharepoint.com/my"
  username: "nessim.esquenazi-ext@pernod-ricard.com"
  password: "Nescho1234$"
  folder_path: "C:\Users\PR061979\OneDrive - Pernod Ricard\Auto RF SO"  # ruta relativa en SharePoint
forecast:
  periods: 12

