sharepoint:
  # Site URL de tu OneDrive for Business (personal)
  site_url: "https://pernodricard-my.sharepoint.com/personal/nessim_esquenazi_ext_pernod_ricard_com"

  # Carpeta relativa dentro de la librería 'Documents'
  folder_path: "Documents/Auto RF SO/data"

  username: "${{ env.SP_USER }}"
  password: "${{ env.SP_PASS }}"

  extract:
    columns:
      - Mercado
      - Canal
      - Cliente anaplan
      - Marca Retrive
      - SKU Pareto
      - SKU h Anaplan
      - Descripcion
      - CC
      - Lista de precios
      - Sucursal
      - Región
      - Scenario
    scenarios:
      - A25
      - RF10
      - RF01

prices:
  file: "data/price_list.csv"

forecast:
  periods: 12


