sharepoint:
  site_url: "https://pernodricard-my.sharepoint.com/my"
  username: "nessim.esquenazi-ext@pernod-ricard.com"
  password: "Nescho1234$"
  folder_path: "https://pernodricard-my.sharepoint.com/my?id=%2Fpersonal%2Fnessim%5Fesquenazi%2Dext%5Fpernod%2Dricard%5Fcom%2FDocuments%2FAuto%20RF%20SO"  # ruta relativa en SharePoint
  extract:
  columns:
    - Mercado
    - Canal
    - Cliente anaplan
    - Marca Retrive
    - SKU Pareto
    - SKU h Anaplan
    - Descripcion
    - CC
    - Lista de precios
    - Sucursal
    - Región
    - Lista de precios
    - Scenario     # si en tus CSV existe esta columna
  scenarios:       # lo veremos en el punto 2
    - A25
    - RF10
    - RF01
prices:
  file: "data/price_list.csv"
forecast:
  periods: 12

