name: Rolling Forecast Manual

# Sólo disparo manual
on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepara credenciales de SharePoint
        run: |
          sed -i "s|\${{ env.SP_USER }}|$SP_USER|g" config/config.yaml
          sed -i "s|\${{ env.SP_PASS }}|$SP_PASS|g" config/config.yaml
        env:
          SP_USER: ${{ secrets.SP_USER }}
          SP_PASS: ${{ secrets.SP_PASS }}

      - name: Run Rolling Forecast
        run: python -m src.main

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add outputs/
          git commit -m "Actualiza forecast $(date +'%Y-%m-%d')" || echo "No hay cambios"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


